### ISSUE TITLE
諸々を監視したい

### ISSUE THREAD

**Issue by gotti** [ueckoken/plarail2021-soft#100]
gRPCシュっとできるぽい
https://github.com/grpc-ecosystem/go-grpc-prometheus#client-side

**Comment by Azuki-bar** [comment]
キリ番おめ

**Comment by gotti** [comment]
gRPCとclient側とでメトリクスのエンドポイントを分けます。/grpc/metricsとかにしてください。

**Comment by gotti** [comment]
client側のメトリクスをゴリゴリやっていきをする

**Comment by Azuki-bar** [comment]
> gRPCとclient側とでメトリクスのエンドポイントを分けます。/grpc/metricsとかにしてください。

#103 で実装しました

**Comment by gotti** [comment]
ある程度片付いたので爆破
