### ISSUE TITLE
websocket i/o timeout

### ISSUE THREAD

**Issue by gotti** [ueckoken/plarail2021-soft#105]
なんかjs→鯖だけタイムアウトで頻繁に切れるしREST使った単純なのにした方がいいかも

**Comment by otariidae** [comment]
あてずっぽうなんですが
https://github.com/ueckoken/plarail2021-soft/blob/b3891a530e0d7b296a402b5ac10d0b439879241f/backend/external/pkg/clientHandler/clientHandler.go#L47-L51
pongを受信したときにcancelしているから、という説はありませんか？

**Comment by gotti** [comment]
ウワーーッ、それでした。ありがとうございます直します

**Comment by gotti** [comment]
治りました!
