### ISSUE TITLE
gRPCのエラーメッセージはメトリクスに載せられない？

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/plarail2021-soft#112]
表題の通りです。
gRPCはエラーを返すときにエラーコードと共にエラーメッセージを返します。

例：
https://github.com/ueckoken/plarail2021-soft/blob/acf607bb879a0c9a0eccf7f20e24834e35e80435/backend/internal/internal/ServeCommand2Internal.go#L27

メトリクス解析時にこのメッセージは取り出せない？

**Comment by Azuki-bar** [comment]
grpcから取り出してオレオレ定義をしないと行けないのかな………
それともgRPCのRicher Error https://grpc.io/docs/guides/error/#richer-error-model を使用する方法でうまくやる方法があるのか

**Comment by gotti** [comment]
爆破
