### ISSUE TITLE
Static Generation vs Server-side Rendering

### ISSUE THREAD

**Issue by otariidae** [ueckoken/plarail2021-soft#147]
ref: https://nextjs.org/docs/basic-features/pages

今後の実装方針としてどちらなのか気になったので
もし完全に静的なら[Static HTML Export](https://nextjs.org/docs/advanced-features/static-html-export)が最も楽だと思います

**Comment by Azuki-bar** [comment]
Static HTML Export, 試しにDockerイメージ作ってみたらImageの最適化まわりが面倒そうだったんですよね。
NextJSが提供するサーバで運用するのがもっとも簡単そうであると思ったのですがいかがでしょう。
@hutinoatari

**Comment by hutinoatari** [comment]
楽な方が良いので Static HTML Export に1票(Dockerイメージはできてると聞きました)
