### ISSUE TITLE
地図の描画

### ISSUE THREAD

**Issue by otariidae** [ueckoken/plarail2021-soft#154]
地図というか路線図というかリアルタイムマップというか、とにかくあの図の描画方法を検討する

地図に含むべきもの：

- 線路
- 駅
- 車両
- ストップレール
- 分岐レール
- （ホールセンサー）
  - バックエンド側の測位のための部品であり、ユーザーに見せる必要はない？

ぱっと思いついた候補：

- 画像
  - 状態によって色とか位置とかを変えたくなった時に不便
- Canvas
  - Reactから扱いにくい
- SVG
  - よさそう

募集：手書きSVG職人（Reactコンポーネントとして）

**Comment by otariidae** [comment]
車両の正確な位置を描画するのは至難の業な気がするので後回しでいいかも

**Comment by hutinoatari** [comment]
ざっとコンポーネントの仕様を考えました、どうでしょう。

## Rail
シマシマ模様。
車両はとりあえず円で表示、後々表示用の車両コンポーネントを作るかも。
車両の位置を表示させるとなると直線が楽、折れ線にするとちょっとメンドそう(頂点の配列を受けてそれぞれの長さの比から表示位置を出すとか)。
位置を表示させないならtrainsをbooleanに変更して真ん中の位置に表示させとくでよさそう(か、線路自体にアニメーションさせるか)。
| プロパティ名 | 型 | 備考 |
| --- | --- | --- |
| startPosition | Point |  |
| endPosition | Point |  |
| trains | number[] | 値は0.0-1.0の範囲 |

## Station
横向き白四角に駅名表示を想定。
ストップレールが上がってる時はなんらかの表示。
| プロパティ名 | 型 | 備考 |
| --- | --- | --- |
| name | String |  |
| position | Point |  |
| isStop | boolean | 強制停車 |

## SwitchPoint
円の中に入車角と出車角の線を表示。
| プロパティ名 | 型 | 備考 |
| --- | --- | --- |
| position | Point |  |
| fromAngle | number | 0.0-360.0 |
| leftOutAngle | number | 0.0-360.0 |
| rightOutAngle | number | 0.0-360.0 |
| isLeft | boolean | 切り替え |

## StopPoint
駅外のストップレール用。
線路に重ねるのを想定。
| プロパティ名 | 型 | 備考 |
| --- | --- | --- |
| position | Point |  |
| isStop | boolean |  |

**Comment by hutinoatari** [comment]
```
interface Point {
    x: number;
    y: number;
}
```

**Comment by otariidae** [comment]
線路をシマシマにすると分岐点が不自然に見える懸念が無きにしも非ずな気がします

**Comment by hutinoatari** [comment]
分岐点を白丸にして継ぎ目が見えないようにしたのでその心配は大丈夫だと思います
