### ISSUE TITLE
速度メーターを表示したい

### ISSUE THREAD

**Issue by otariidae** [ueckoken/plarail2021-soft#165]
でも速度は測位点を通過したときのみ算出されるため、リアルタイムの速度を知る方法はないらしい。

この制約のうえでどうにか速度メーターを実現する案：

- 速度制御APIに送る値をそのまま速度として表示する
  - つまらなそう
  - まるで連続的に速度変化したように見せかけるために投機的に架空の値を表示する？
- ほかの方法でどうにかリアルタイム速度がわかるAPIを作ってもらう
  - モーターをPWM制御しているプログラムは速度を知ることができるのでは？
    - ほんとうですか？ cc: @ta729ip

**Comment by ta729ip** [comment]
PWM制御をするプログラム側で速度を調べることですが、可能だと思います。事前にPWMのデューティ比に対するモーターの回転数を調べ、PWMのデューティ比と回転数が対応付けられれば、そこから速度の大小は分かるかと思います。

**Comment by otariidae** [comment]
とりあえず見た目だけ作っておきたい。メーター感があればよいので単位とかはひとまず不要

**Comment by Azuki-bar** [comment]
スピードを返すAPIを速度制御をするラズパイに生やしてみましょうか？

**Comment by Azuki-bar** [comment]
> スピードを返すAPIを速度制御をするラズパイに生やしてみましょうか？

サーバ構成的に厳しいかもしれません。ラズパイのAPIを叩くプロキシサーバが必要になりますね。。。。
