### ISSUE TITLE
配信映像を表示する

### ISSUE THREAD

**Issue by otariidae** [ueckoken/plarail2021-soft#183]
車載カメラの映像がWebRTCで配信されるようなので、それを表示する
ドキュメントはまだないっぽいけど、`frontend/videoCast` に昔の実装の名残があるらしいので参考にする

**Comment by otariidae** [comment]
[エンドポイント](https://github.com/ueckoken/plarail2021-soft/blob/main/docs/endpoints.md)のドキュメントによると [receiver-test.chofufes2021.gotti.dev](https://receiver-test.chofufes2021.gotti.dev) で昔の実装が動いているらしい

**Comment by otariidae** [comment]
WebRTCのご経験があるとのことでしたので、とりあえずメンションしておきます @csenet

**Comment by ruu413** [comment]
frontend/videoCast/one_to_multiple_cast_skyway.pyが
wss://webrtc.chofufes2021.gotti.dev/
frontend/videoCast/skyway_receiver.htmlが
https://receiver-test.chofufes2021.gotti.dev/
frontend/videoCast/momo_sender.htmlが
https://webrtc-sender.chofufes2021.gotti.dev/
で動いています
momo_sender.htmlでカメラ接続後ソース, ルーム名を指定してconnect receiverをクリックすることで配信できます
skyway_receiver.htmlでは, skyway_receiver_.jsを読み込み, 
window.openVideoConnection("html id名", "ルーム名")
で接続され,
window.closeVideoConnection("ルーム名")
で切断されます

momo(ラズパイ)で配信する場合は
momo https://momo.shiguredo.jp/ をダウンロード後,
.\momo --no-audio-device ayame wss://ayame-labo.shiguredo.jp/signaling ruu413@ayame-momo --signaling-key シグナリングキーで接続できます
生JS, Pythonで実装していて, コードもきれいでない自覚はあるので全取り換えしてもらっても構いません

**Comment by ruu413** [comment]
@csenet 今作業中でしたがアサインしてませんでしたごめんなさい
