### ISSUE TITLE
ストップレールの見た目

### ISSUE THREAD

**Issue by otariidae** [ueckoken/plarail2021-soft#240]
2灯の信号（停止と進行）にすればそれっぽいのでは？と思いついた

**Comment by otariidae** [comment]
https://github.com/ueckoken/plarail2021-soft/blob/a3982c4ef4b20e371052b4ad36b777a04ed67d1a/backend/proto/statesync.proto#L10-L14

`UNKNOWN` ってどう表示するの...？

**Comment by gotti** [comment]
unknownは念の為とりあえず追加しているだけで使う予定はないです。コンソールにエラー吐くとかで。
