### ISSUE TITLE
フロントエンドとのAPIのすり合わせ

### ISSUE THREAD

**Issue by gotti** [ueckoken/plarail2021-soft#264]
これでいきます。大丈夫ですかね？

# スピード制御
## エンドポイント
`wss://speed.chofufes2021.gotti.dev/speed`

## データ構造
json
```
train_name: 電車の名前(string、以下に一覧があります。操作可能なのはTAKAO,CHICHIBUのみ。他はどうなるかわかりません。)
speed: スピード(intで-100<=speed<=100)
```
https://github.com/ueckoken/plarail2021-soft/blob/main/backend/proto/speedControl.proto

# 位置情報
## エンドポイント
`wss://positioning.chofufes2021.gotti.dev/subscribePosition`

## データ構造
json
```
train_name: 電車の名前(string、スピード制御と同じ。ただし他の名前も測位には出てきます。)
hall_name: 通過したホールセンサー名(以下のURL参照。
duration: 次のセンサーまでの、いままでの平均の所要時間(単位は秒でfloat64)
fetched_at: 通過したときのunixtime(float64)
```
https://github.com/ueckoken/plarail2021-soft/blob/main/backend/positioning/pkg/hallsensor/embed/hallsensor.yaml

**Comment by Azuki-bar** [comment]
LGTM

**Comment by otariidae** [comment]
LGTM
ところでホールセンサー名と地図上での位置関係はどこを見ればわかりますか？

**Comment by gotti** [comment]
あ、スピード制御はそのjsonを送受信して、位置情報は受信のみです。

**Comment by otariidae** [comment]
[ホールセンサーの地図](https://github.com/ueckoken/plarail2021-soft/blob/861ff7599ac8e02e8ec02065d8ce10dc3ba97b17/docs/section-where-positioning-is-possible.pdf) には矢印が書いてあるんですが、電車が進む方向はあらかじめ決まっていますか？そうなるとスピード制御APIに逆向きに進むよう送信しても効かないですか？

**Comment by gotti** [comment]
電車が進む方向は決まっています。が、スピード制御APIには逆向きは進むよう送信できるので測位の方がバグります。。
