### ISSUE TITLE
fix goroutine leak on internal control server

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/plarail2021-soft#340]

**Comment by Azuki-bar** [comment]
#199

**Comment by gotti** [comment]
なんかleakしなくなったので様子見

**Comment by gotti** [comment]
たぶんpingするやつがleakしてて、esp32がdownしてるとleakする

**Comment by gotti** [comment]
勘弁してくれ
https://zenn.dev/cube/articles/4ce18a672fc991

**Comment by gotti** [comment]
ええ変わらない
![image](https://user-images.githubusercontent.com/18141824/142729898-4027b3df-a4dc-4e2b-b9f1-ac3ab0bc7f8b.png)

**Comment by gotti** [comment]
わかったdeferが効いてないじゃんねこれ

**Comment by gotti** [comment]
:heavy_check_mark: fixed
![image](https://user-images.githubusercontent.com/18141824/142730226-e4f7a502-aab2-4fb5-a8b4-37031b83e688.png)
