### ISSUE TITLE
フロントエンドどこに残しますか

### ISSUE THREAD

**Issue by gotti** [ueckoken/plarail2021-soft#441]
今はe2-medium*1でフロントエンドが動いてるんですがこれを落としたいです。
ぼくの鯖か工研のgithub pagesにでもフロントエンドを残しておきたいですね。どうしましょうか。

**Comment by Azuki-bar** [comment]
github pagesで良いと思います

**Comment by Azuki-bar** [comment]
もし github pagesに残すならば適当にNextでbuildした結果をどこかのディレクトリに置かないといけませんね

**Comment by gotti** [comment]
ok、ドメインはどうしますか。cloudflare dnsのリダイレクトはルール使わないといけなくてfreeなのでルール3つしか書けないけど

**Comment by gotti** [comment]
ueckokenのユーザーのvercelに移したのでclose
